<?php
require_once('includePHP/head.php');
?>
<?php
require_once('includePHP/giratorio.php');
require_once('includePHP/navbar.php');
require_once('testPHP/carrusel.php');
require_once('includePHP/acercade.php');
require_once('includePHP/iniciodeloshechos.php');
require_once('includePHP/caracteristicasdeinicio.php');
require_once('includePHP/videmodal.php');
require_once('includePHP/servicios.php');
require_once('includePHP/proyectos.php');
require_once('includePHP/volverarriba.php');
require_once('includePHP/footer.php');
require_once('includePHP/copyright.php');
require_once('includePHP/libreriajavascript.php');
?>